services:
  # ---------- Reverse proxy with HTTPS ----------
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

  # ---------- Placeholder API (will become FastAPI) ----------
  api:
    image: nginx:alpine
    restart: always
    command:
      - sh
      - -c
      - |
        echo 'CiviSort API coming soon' > /usr/share/nginx/html/index.html
        nginx -g 'daemon off;'

  # ---------- pgAdmin web UI ----------
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@civisort.org
      PGADMIN_DEFAULT_PASSWORD: civisort
    ports:
      - "5050:80"
    depends_on:
      - db

  # ---------- Springfield ----------
  springfield_permits_pw:
    build:
      context: ./scrapers/springfield_permits_pw
    depends_on:
      - db
    restart: "no"

  city_meetings:
    build:
      context: ./scrapers/city_meetings
    depends_on:
      - db
    restart: "no"

  # ---------- Sangamon County ----------
  county_board:
    build:
      context: ./scrapers/county_board
    depends_on:
      - db
    restart: "no"

  county_permits:
    build:
      context: ./scrapers/county_permits
    depends_on:
      - db
    restart: "no"

volumes:
  caddy_data:
  caddy_config:
  pgadmin_data:
